version: "3.8"
services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "8000:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro    
            - ./src:/var/www/laravel
        depends_on:
            - mysql
            - php

    # PHP Service
    php:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - ./src:/var/www/laravel        


    # Database Server
    mysql:
        image: mysql:8.0
        ports:
            - "3316:3306"
        env_file:
            - env/mysql.env
        volumes:
            - db_data:/var/lib/mysql
    
    # PhpMyAdmin
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        environment: 
            - PMA_HOST=mysql
            - PMA_PORT=3306
        ports:
            - 8001:80

    # Composer
    composer:
        build:
            context: dockerfiles
            dockerfile: composer.Dockerfile
        volumes:
            - ./src:/var/www/laravel
    
    artisan:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - ./src:/var/www/laravel
        entrypoint: ["php", "/var/www/laravel/artisan"]

     # Для сборки js
    node:
        build:
            context: dockerfiles
            dockerfile: node.Dockerfile
        tty: true
        working_dir: /var/www/laravel
        volumes:
            - ./src:/var/www/laravel  


volumes:
    db_data:



